# Generated by Django 5.0.1 on 2026-02-04 08:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='data_dolaczenia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AddField(
            model_name='profil',
            name='wiek',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Wiek'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, verbose_name='O mnie / Osiągnięcia'),
        ),
    ]
