# Generated by Django 5.2.8 on 2026-02-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profil_data_dolaczenia_profil_miejscowosc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ulubiona_metoda',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ulubiona metoda'),
        ),
    ]
