# Generated by Django 5.2.8 on 2026-02-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profil_ulubiona_metoda'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='obserwuje',
            field=models.ManyToManyField(blank=True, related_name='obserwujacy', to='users.profil'),
        ),
    ]
