# Generated by Django 5.0.1 on 2026-02-04 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa łowiska')),
                ('miejscowosc', models.CharField(max_length=100, verbose_name='Miejscowość')),
            ],
        ),
        migrations.CreateModel(
            name='Polow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek_ryby', models.CharField(max_length=90, verbose_name='Gatunek ryby')),
                ('waga_ryby', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True)),
                ('dlugosc_ryby', models.PositiveIntegerField(blank=True, help_text='cm', null=True)),
                ('data_polowu', models.DateTimeField(auto_now_add=True)),
                ('zdjecie_ryby', models.ImageField(blank=True, null=True, upload_to='zdjecia_ryb/')),
                ('opis', models.TextField(blank=True, verbose_name='Dodatkowe informacje')),
                ('lowisko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lowisko', verbose_name='Miejsce połowu')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polowy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
