# Generated by Django 5.2.8 on 2026-02-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowisko',
            options={'verbose_name': 'Łowisko', 'verbose_name_plural': 'Łowiska'},
        ),
        migrations.AlterModelOptions(
            name='polow',
            options={'verbose_name': 'Połów', 'verbose_name_plural': 'Połowy'},
        ),
        migrations.AddField(
            model_name='lowisko',
            name='lat',
            field=models.FloatField(default=52.4, verbose_name='szerokość geograficzna (Lat)'),
        ),
        migrations.AddField(
            model_name='lowisko',
            name='lon',
            field=models.FloatField(default=21.0, verbose_name='długość geograficzna (Lon)'),
        ),
    ]
