# Generated by Django 5.2.8 on 2026-02-18 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='polow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.polow'),
        ),
    ]
