# Generated by Django 5.2.8 on 2026-02-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_komentarz_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('czy_przeczytana', models.BooleanField(default=False)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyslane_wiadomosci', to=settings.AUTH_USER_MODEL)),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odebrane_wiadomosci', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_wyslania'],
            },
        ),
    ]
