# Generated by Django 5.2.8 on 2026-02-26 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_wiadomosc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('obserwacja', 'Nowy obserwujący')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('czy_przeczytane', models.BooleanField(default=False)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powiadomienia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
